# This file has been generated by mvnix 0.1.0. Configure the build here!
{ pkgs ? import <nixpkgs> { inherit system; }
, system ? builtins.currentSystem
, mavenix ? pkgs.callPackage (import ./nix/mavenix.nix) {}
}: with pkgs; let
  jar = mavenix {
    src = ./.;
    infoFile = ./nix/mavenix-info.json;
    #maven = maven.override { jdk = oraclejdk10; };
  };
in jar // {
  bin = runCommand "ivy-convertpom" { buildInputs = [ makeWrapper ]; } ''
    mkdir -p $out/bin
    jar_file=`echo ${jar.build}/share/java/ivy-convertpom-*-jar-with-dependencies.jar`
    makeWrapper ${jar.maven.jdk}/bin/java $out/bin/ivy-convertpom \
      --add-flags "-jar $jar_file"
  '';
}
